name: Update Changelog
on:
  release:
    types: [created, edited]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
    - name: Build the Changelog
      uses: ardalanamini/auto-changelog@v4
      id: build-changelog
      with:
        github-token: ${{ github.token }}
        commit-types: |
          feature: ğŸŒŸ New Features
          fix: ğŸ Bug Fixes
          perf: ğŸš€ Performance Improvements
          docs: ğŸ“– Documentation
          build: ğŸ”¨ Build Adjustments
          test: ğŸ“› Tests
          ci: ğŸ”„ Continuous Integrations
          refactor: ğŸ“ Refactored
          style: ğŸ¨ Code Style Adjustments
        default-commit-type: ğŸ“‚ Other Adjustments